import { readFile, writeFile } from "node:fs/promises";
import {
  analyzeDeckBattleReport,
  type DeckBattleInsightsReport,
} from "../src/game/deckBattleInsights";
import { getDeckBenchmarkSuite, type DeckBenchmarkSuiteId } from "../src/game/deckBenchmarkSuites";
import {
  scoreDeckBattleResults,
  type DeckBattleScoreEntry,
  type DeckBattleScoringReport,
} from "../src/game/deckBattleScoring";

interface CliOptions {
  reportPaths: string[];
  outPath: string;
  defaultSuiteId?: DeckBenchmarkSuiteId;
}

interface SnapshotSuiteData {
  summary: {
    suiteId: DeckBenchmarkSuiteId;
    seedStart: number;
    count: number;
    aiProfile: DeckBattleScoringReport["options"]["aiProfile"];
    firstPlayerMode: DeckBattleScoringReport["options"]["firstPlayerMode"];
    decks: number;
    games: number;
    failures: number;
    warnings: number;
    averageSteps: number;
    averageTurns: number;
  };
  scores: ReturnType<typeof scoreSnapshot>[];
  insights: DeckBattleInsightsReport;
}

const options = parseArgs(process.argv.slice(2));
if (options.reportPaths.length === 0) {
  throw new Error("At least one --report path is required");
}

const reports = await Promise.all(
  options.reportPaths.map(async (path) => JSON.parse(await readFile(path, "utf8")) as DeckBattleScoringReport),
);
const suites = reports.map(toSnapshotSuiteData);
const defaultSuiteId = options.defaultSuiteId ?? suites.at(-1)?.summary.suiteId ?? suites[0].summary.suiteId;

await writeFile(options.outPath, formatSnapshotModule(suites, defaultSuiteId));
console.log(`Wrote ${options.outPath}`);
console.log(`Suites: ${suites.map((suite) => suite.summary.suiteId).join(", ")}`);
console.log(`Default: ${defaultSuiteId}`);

function toSnapshotSuiteData(report: DeckBattleScoringReport): SnapshotSuiteData {
  const suiteDeckIds = getDeckBenchmarkSuite(report.options.suiteId).deckPresetIds;
  const deckPresetIds = suiteDeckIds.slice(0, report.options.maxDecks ?? suiteDeckIds.length);
  const decks = scoreDeckBattleResults(deckPresetIds, report.games);
  const enrichedReport: DeckBattleScoringReport = { ...report, decks };
  return {
    summary: {
      suiteId: report.options.suiteId,
      seedStart: report.options.seedStart,
      count: report.options.count,
      aiProfile: report.options.aiProfile,
      firstPlayerMode: report.options.firstPlayerMode ?? "player",
      decks: report.summary.decks,
      games: report.summary.games,
      failures: report.summary.failures,
      warnings: report.summary.warnings,
      averageSteps: report.summary.averageSteps,
      averageTurns: report.summary.averageTurns,
    },
    scores: decks.map((deck, index) => scoreSnapshot(deck, index + 1)),
    insights: analyzeDeckBattleReport(enrichedReport),
  };
}

function scoreSnapshot(deck: DeckBattleScoreEntry, rank: number) {
  return {
    rank,
    deckPreset: deck.deckPreset,
    sourceDeckId: deck.sourceDeckId,
    battleScore: deck.battleScore,
    practicalScore: deck.practicalScore,
    winRate: deck.winRate,
    winPointRate: deck.winPointRate,
    stabilityScore: deck.stabilityScore,
    speedScore: deck.speedScore,
    games: deck.games,
    wins: deck.wins,
    losses: deck.losses,
    draws: deck.draws,
    playerSideWinPointRate: deck.playerSideWinPointRate,
    cpuSideWinPointRate: deck.cpuSideWinPointRate,
    firstPlayerWinPointRate: deck.firstPlayerWinPointRate,
    secondPlayerWinPointRate: deck.secondPlayerWinPointRate,
    failures: deck.failures,
    warnings: deck.warnings,
    averageSteps: deck.averageSteps,
    averageTurns: deck.averageTurns,
    matchups: deck.matchups,
  };
}

function formatSnapshotModule(suites: SnapshotSuiteData[], defaultSuiteId: DeckBenchmarkSuiteId): string {
  const suiteUnion = suites.map((suite) => JSON.stringify(suite.summary.suiteId)).join(" | ");
  return `import type { DeckBattleInsightCategory, DeckBattleProblemFocusSummary, DeckBattleProblemGame } from "./deckBattleInsights";
import type { DeckBenchmarkSuiteId } from "./deckBenchmarkSuites";
import type { DeckBattleMatchupKey, DeckBattleMatchupStats } from "./deckBattleScoring";
import type { DeckPresetId, DeckSubmissionPresetId } from "./deckPresets";

// Generated by scripts/generate-deck-battle-snapshots.ts.
// Source artifacts are created by npm run score:deck-battles and npm run analyze:deck-battles.
export type DeckBattleScoreSnapshotSuiteId = Extract<DeckBenchmarkSuiteId, ${suiteUnion}>;

export interface DeckBattleScoreSnapshotSummary {
  suiteId: DeckBattleScoreSnapshotSuiteId;
  seedStart: number;
  count: number;
  aiProfile: "stable" | "strong";
  firstPlayerMode: "player" | "cpu" | "alternate" | "both";
  decks: number;
  games: number;
  failures: number;
  warnings: number;
  averageSteps: number;
  averageTurns: number;
}

export interface DeckBattleScoreSnapshot {
  rank: number;
  deckPreset: DeckSubmissionPresetId;
  sourceDeckId: number;
  battleScore: number;
  practicalScore: number;
  winRate: number;
  winPointRate: number;
  stabilityScore: number;
  speedScore: number;
  games: number;
  wins: number;
  losses: number;
  draws: number;
  playerSideWinPointRate: number;
  cpuSideWinPointRate: number;
  firstPlayerWinPointRate: number;
  secondPlayerWinPointRate: number;
  failures: number;
  warnings: number;
  averageSteps: number;
  averageTurns: number;
  matchups: Record<DeckBattleMatchupKey, DeckBattleMatchupStats>;
}

export interface DeckBattleScoreSnapshotSuite {
  summary: DeckBattleScoreSnapshotSummary;
  scores: DeckBattleScoreSnapshot[];
  categories: DeckBattleInsightCategory[];
  problemGames: DeckBattleProblemGame[];
  problemFocuses: DeckBattleProblemFocusSummary[];
  recommendedFocus: string[];
}

export const DEFAULT_DECK_BATTLE_SCORE_SNAPSHOT_SUITE_ID = ${JSON.stringify(defaultSuiteId)} as DeckBattleScoreSnapshotSuiteId;

export const DECK_BATTLE_SCORE_SNAPSHOT_SUITES = ${JSON.stringify(suites.map((suite) => ({
    summary: suite.summary,
    scores: suite.scores,
    categories: suite.insights.categories,
    problemGames: suite.insights.problemGames,
    problemFocuses: suite.insights.problemFocuses,
    recommendedFocus: suite.insights.recommendedFocus,
  })), null, 2)} as const satisfies readonly DeckBattleScoreSnapshotSuite[];

export function getDeckBattleScoreSuite(
  suiteId: DeckBattleScoreSnapshotSuiteId = DEFAULT_DECK_BATTLE_SCORE_SNAPSHOT_SUITE_ID,
): DeckBattleScoreSnapshotSuite {
  return DECK_BATTLE_SCORE_SNAPSHOT_SUITES.find((suite) => suite.summary.suiteId === suiteId) ?? DECK_BATTLE_SCORE_SNAPSHOT_SUITES[0];
}

export function getDeckBattleScoreSnapshot(
  deckPreset: DeckPresetId,
  suiteId: DeckBattleScoreSnapshotSuiteId = DEFAULT_DECK_BATTLE_SCORE_SNAPSHOT_SUITE_ID,
): DeckBattleScoreSnapshot | undefined {
  const suite = getDeckBattleScoreSuite(suiteId);
  return suite.scores.find((score) => score.deckPreset === deckPreset);
}
`;
}

function parseArgs(args: string[]): CliOptions {
  const parsed: CliOptions = {
    reportPaths: [],
    outPath: "src/game/deckBattleScoreSnapshots.ts",
  };

  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i];
    const next = args[i + 1];
    if (arg === "--report") {
      parsed.reportPaths.push(readString(arg, next));
      i += 1;
    } else if (arg === "--out") {
      parsed.outPath = readString(arg, next);
      i += 1;
    } else if (arg === "--default-suite") {
      parsed.defaultSuiteId = readString(arg, next) as DeckBenchmarkSuiteId;
      i += 1;
    } else if (arg === "--help" || arg === "-h") {
      printHelp();
      process.exit(0);
    } else {
      throw new Error(`Unknown option: ${arg}`);
    }
  }

  return parsed;
}

function readString(name: string, value: string | undefined): string {
  if (!value) {
    throw new Error(`${name} requires a value`);
  }
  return value;
}

function printHelp(): void {
  console.log(`
Usage:
  npm run generate:deck-battle-snapshots -- [options]

Options:
  --report <path>         Input report.json. Can be repeated.
  --out <path>            Output TS module. Default: src/game/deckBattleScoreSnapshots.ts
  --default-suite <id>    Default suite used in UI. Defaults to the last report.
`);
}
